- namespace: App\Dto\Repository\UserRepository
  class: UserDto
  properties:
    id: int
    name: string
    email: string
    password: string
    token: string
    created_at: string
    updated_at: string
